name: EzChestShop
version: ${project.version}
main: me.deadlight.ezchestshop.EzChestShop
api-version: 1.16
folia-supported: true
depend:
  - account-provider
softdepend:
  - Vault
  - WildChests
  - WorldGuard
  - Slimefun #in case just to load after the Slimefun
  - Multiverse-Core #preventing null worlds
  - CMI
  - PlaceholderAPI
  - Towny
  - AdvancedRegionMarket
  - ItemsAdder
authors: [ItzAmirreza, ElitoGame]
description: ${project.description}
commands:
  cs:
    description: create or delete a shop
    aliases:
      - cshop
      - chestshop
  csadmin:
    description: commands designed for admins to moderate
  checkprofits:
    description: Check all your shop profits that you made offline!
    aliases:
      - cp
